# Generated by Django 5.1.3 on 2024-11-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
                ('date', models.CharField(max_length=200, verbose_name='Дата и время')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dress_code', models.CharField(max_length=600, verbose_name='Треюования к одежде')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinavin_app.category', verbose_name='Выберите Категорию')),
            ],
            options={
                'verbose_name': 'Название события',
                'verbose_name_plural': 'Название события',
            },
        ),
    ]
